import type { Incident, Campus } from '@/types';

export const DEMO_CAMPUSES: Campus[] = [
  {
    id: 'campus-demo-university',
    name: 'Demo University',
    city: 'Los Angeles',
    state: 'CA',
    lat: 34.0689,
    lng: -118.4452,
    hillel_contact: 'hillel@demo-university.edu',
  },
  {
    id: 'campus-cal-state-la',
    name: 'Cal State LA',
    city: 'Los Angeles',
    state: 'CA',
    lat: 34.0689,
    lng: -118.1717,
    hillel_contact: null,
  },
  {
    id: 'campus-usc',
    name: 'University of Southern California',
    city: 'Los Angeles',
    state: 'CA',
    lat: 34.0224,
    lng: -118.2851,
    hillel_contact: 'hillel@usc.edu',
  },
];

export const DEMO_INCIDENTS: Incident[] = [
  // --- Westwood (campus-demo-university assigned to 8 incidents) ---
  {
    id: 'demo-incident-001',
    category: 'harassment',
    description:
      'An individual shouted antisemitic slurs at a group of students leaving a kosher restaurant on Westwood Boulevard, directing specific threats at those wearing kippot and calling them "invaders." The suspect fled before police arrived.',
    occurred_at: '2024-01-14T18:30:00Z',
    neighborhood: 'Westwood',
    lat: 34.0647,
    lng: -118.4476,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: 'campus-demo-university',
    created_at: '2024-01-15T09:00:00Z',
  },
  {
    id: 'demo-incident-002',
    category: 'vandalism',
    description:
      'A Star of David carved into the wall of a campus Hillel building was defaced with a swastika spray-painted in red directly over it. The graffiti was discovered by staff on a Monday morning. Estimated repair cost: $650.',
    occurred_at: '2024-02-09T23:00:00Z',
    neighborhood: 'Westwood',
    lat: 34.0627,
    lng: -118.4472,
    severity: 'high',
    source: 'ADL',
    status: 'verified',
    campus_id: 'campus-demo-university',
    created_at: '2024-02-10T08:30:00Z',
  },
  {
    id: 'demo-incident-003',
    category: 'online_threat',
    description:
      'The Hillel chapter at a Westwood university received an anonymous email containing a detailed threat to disrupt their Shabbat dinner, referencing the address and specific event time. IT security and campus police were immediately notified.',
    occurred_at: '2024-03-22T14:15:00Z',
    neighborhood: 'Westwood',
    lat: 34.0656,
    lng: -118.4446,
    severity: 'high',
    source: 'community',
    status: 'verified',
    campus_id: 'campus-demo-university',
    created_at: '2024-03-22T16:00:00Z',
  },
  {
    id: 'demo-incident-004',
    category: 'harassment',
    description:
      'Three Jewish students were surrounded by a group of individuals near the campus library who chanted slogans and refused to let them pass for several minutes. Campus security responded but the group dispersed before arrival.',
    occurred_at: '2024-04-18T12:45:00Z',
    neighborhood: 'Westwood',
    lat: 34.0620,
    lng: -118.4466,
    severity: 'medium',
    source: 'LAPD',
    status: 'verified',
    campus_id: 'campus-demo-university',
    created_at: '2024-04-18T14:00:00Z',
  },
  {
    id: 'demo-incident-005',
    category: 'vandalism',
    description:
      'Mezuzot were ripped from doorframes in a Westwood apartment building known to house Jewish students. Three units were affected. The word "leave" was scratched into one of the doorframes. Police filed a hate crime report.',
    occurred_at: '2024-06-03T01:30:00Z',
    neighborhood: 'Westwood',
    lat: 34.0642,
    lng: -118.4480,
    severity: 'high',
    source: 'LAPD',
    status: 'verified',
    campus_id: 'campus-demo-university',
    created_at: '2024-06-03T10:00:00Z',
  },
  {
    id: 'demo-incident-006',
    category: 'harassment',
    description:
      'A Jewish student wearing a Star of David necklace was approached by an individual outside Westwood Ralphs who demanded she "go back to Israel" and filmed her without consent while making threatening gestures.',
    occurred_at: '2024-07-27T16:00:00Z',
    neighborhood: 'Westwood',
    lat: 34.0633,
    lng: -118.4483,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: 'campus-demo-university',
    created_at: '2024-07-27T18:30:00Z',
  },
  {
    id: 'demo-incident-007',
    category: 'online_threat',
    description:
      'A student-run Jewish cultural organization received a coordinated attack on their Instagram account, including dozens of accounts posting Holocaust denial imagery and threatening DMs referencing the club\'s next scheduled event location.',
    occurred_at: '2024-09-11T21:00:00Z',
    neighborhood: 'Westwood',
    lat: 34.0654,
    lng: -118.4451,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: 'campus-demo-university',
    created_at: '2024-09-12T09:00:00Z',
  },
  {
    id: 'demo-incident-008',
    category: 'vandalism',
    description:
      'The bulletin board of the campus Jewish Student Union was torn down and its notices replaced with antisemitic flyers overnight. Security camera footage showed a hooded individual, but the image quality was insufficient for identification.',
    occurred_at: '2024-10-30T03:00:00Z',
    neighborhood: 'Westwood',
    lat: 34.0613,
    lng: -118.4461,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: 'campus-demo-university',
    created_at: '2024-10-30T08:00:00Z',
  },
  // --- Beverly Hills ---
  {
    id: 'demo-incident-009',
    category: 'harassment',
    description:
      'A group of men followed a family leaving Friday night Shabbat services at a Beverly Hills synagogue for two blocks, shouting slurs and filming them. The family reported feeling their safety was threatened and called 911.',
    occurred_at: '2024-01-26T21:00:00Z',
    neighborhood: 'Beverly Hills',
    lat: 34.0747,
    lng: -118.4022,
    severity: 'high',
    source: 'ADL',
    status: 'verified',
    campus_id: null,
    created_at: '2024-01-27T09:00:00Z',
  },
  {
    id: 'demo-incident-010',
    category: 'vandalism',
    description:
      'A Jewish-owned jewelry store on Rodeo Drive had its storefront window spray-painted with antisemitic imagery overnight. The owner discovered it upon opening. Cost of damage was approximately $2,200 including professional cleaning.',
    occurred_at: '2024-03-05T02:00:00Z',
    neighborhood: 'Beverly Hills',
    lat: 34.0727,
    lng: -118.3981,
    severity: 'medium',
    source: 'LAPD',
    status: 'verified',
    campus_id: null,
    created_at: '2024-03-05T09:00:00Z',
  },
  {
    id: 'demo-incident-011',
    category: 'online_threat',
    description:
      'A Beverly Hills synagogue\'s website was defaced with antisemitic text and imagery for approximately four hours before the server provider took it down. An anonymous group claimed responsibility on Telegram.',
    occurred_at: '2024-05-14T08:00:00Z',
    neighborhood: 'Beverly Hills',
    lat: 34.0761,
    lng: -118.3997,
    severity: 'medium',
    source: 'CSI',
    status: 'verified',
    campus_id: null,
    created_at: '2024-05-14T12:00:00Z',
  },
  {
    id: 'demo-incident-012',
    category: 'harassment',
    description:
      'An elderly man wearing traditional Jewish dress was verbally assaulted by a driver who stopped his vehicle and shouted "Jews control everything" before accelerating away. The victim was uninjured but shaken.',
    occurred_at: '2024-08-19T10:30:00Z',
    neighborhood: 'Beverly Hills',
    lat: 34.0720,
    lng: -118.4018,
    severity: 'low',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-08-19T14:00:00Z',
  },
  {
    id: 'demo-incident-013',
    category: 'vandalism',
    description:
      'Swastika stickers were found plastered across the entrance pillars of a Beverly Hills community center the morning before a Jewish cultural event was scheduled. Event security was enhanced as a precaution.',
    occurred_at: '2024-11-07T07:00:00Z',
    neighborhood: 'Beverly Hills',
    lat: 34.0739,
    lng: -118.4024,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-11-07T08:30:00Z',
  },
  // --- Pico-Robertson ---
  {
    id: 'demo-incident-014',
    category: 'harassment',
    description:
      'An individual shouted antisemitic slurs at a group of students leaving a kosher restaurant on Pico Boulevard, directing specific threats at those wearing kippot. Witnesses reported the suspect made references to a recent attack on a synagogue before fleeing.',
    occurred_at: '2024-02-15T19:45:00Z',
    neighborhood: 'Pico-Robertson',
    lat: 34.0520,
    lng: -118.3873,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-02-15T21:00:00Z',
  },
  {
    id: 'demo-incident-015',
    category: 'vandalism',
    description:
      'The exterior wall of a kosher bakery on Pico Boulevard was spray-painted with a swastika and the phrase "not welcome here." The owner had previously reported suspicious individuals loitering near the store. Estimated damage: $900.',
    occurred_at: '2024-04-07T01:00:00Z',
    neighborhood: 'Pico-Robertson',
    lat: 34.0491,
    lng: -118.3848,
    severity: 'high',
    source: 'ADL',
    status: 'verified',
    campus_id: null,
    created_at: '2024-04-07T08:00:00Z',
  },
  {
    id: 'demo-incident-016',
    category: 'harassment',
    description:
      'A woman in a head covering consistent with religious Jewish dress was confronted by two individuals outside a Robertson Boulevard restaurant who made threats referencing her ethnicity and photographed her without consent.',
    occurred_at: '2024-06-20T13:15:00Z',
    neighborhood: 'Pico-Robertson',
    lat: 34.0529,
    lng: -118.3854,
    severity: 'low',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-06-20T15:30:00Z',
  },
  {
    id: 'demo-incident-017',
    category: 'online_threat',
    description:
      'A popular Pico-Robertson area synagogue\'s Facebook page received a coordinated wave of antisemitic comments and threats referencing violent attacks on houses of worship. Over 200 hateful comments were posted before moderators intervened.',
    occurred_at: '2024-09-03T17:00:00Z',
    neighborhood: 'Pico-Robertson',
    lat: 34.0507,
    lng: -118.3879,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-09-04T09:00:00Z',
  },
  {
    id: 'demo-incident-018',
    category: 'assault',
    description:
      'A Jewish man wearing a kippah was shoved from behind while walking on Pico Boulevard and called a derogatory slur. The suspect fled on a bicycle. The victim suffered a minor wrist injury from the fall and filed a police report.',
    occurred_at: '2024-11-22T20:30:00Z',
    neighborhood: 'Pico-Robertson',
    lat: 34.0525,
    lng: -118.3876,
    severity: 'high',
    source: 'LAPD',
    status: 'verified',
    campus_id: null,
    created_at: '2024-11-22T22:00:00Z',
  },
  // --- Fairfax District ---
  {
    id: 'demo-incident-019',
    category: 'vandalism',
    description:
      'Jewish-themed murals on Fairfax Avenue were defaced with antisemitic graffiti including symbols associated with white supremacist groups. Multiple properties were affected over a stretch of three blocks. Community cleanup organized within 48 hours.',
    occurred_at: '2024-01-30T03:30:00Z',
    neighborhood: 'Fairfax District',
    lat: 34.0816,
    lng: -118.3620,
    severity: 'medium',
    source: 'ADL',
    status: 'verified',
    campus_id: null,
    created_at: '2024-01-30T09:00:00Z',
  },
  {
    id: 'demo-incident-020',
    category: 'harassment',
    description:
      'During a community Purim celebration on Fairfax Avenue, individuals in a passing vehicle hurled antisemitic insults at costumed attendees and threw a bottle toward the crowd. No injuries were reported but several attendees were frightened.',
    occurred_at: '2024-03-24T20:00:00Z',
    neighborhood: 'Fairfax District',
    lat: 34.0776,
    lng: -118.3598,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-03-25T08:00:00Z',
  },
  {
    id: 'demo-incident-021',
    category: 'vandalism',
    description:
      'A Holocaust memorial plaque on the exterior of a Fairfax District Jewish deli was pried off and stolen. The deli owner reported it was the third time in two years that the memorial had been targeted.',
    occurred_at: '2024-05-28T23:00:00Z',
    neighborhood: 'Fairfax District',
    lat: 34.0800,
    lng: -118.3633,
    severity: 'high',
    source: 'ADL',
    status: 'verified',
    campus_id: null,
    created_at: '2024-05-29T09:00:00Z',
  },
  {
    id: 'demo-incident-022',
    category: 'harassment',
    description:
      'A rabbi was verbally confronted outside his synagogue on Fairfax Avenue by an individual who made specific threats about Jewish leadership. The suspect was known to police from prior incidents and was later located for questioning.',
    occurred_at: '2024-08-12T11:00:00Z',
    neighborhood: 'Fairfax District',
    lat: 34.0784,
    lng: -118.3587,
    severity: 'high',
    source: 'LAPD',
    status: 'verified',
    campus_id: null,
    created_at: '2024-08-12T13:00:00Z',
  },
  {
    id: 'demo-incident-023',
    category: 'other',
    description:
      'A Jewish community center on Melrose Avenue received a suspicious package. Bomb squad responded and determined it contained antisemitic literature and no explosive material. The package was postmarked from within Los Angeles.',
    occurred_at: '2024-10-09T09:30:00Z',
    neighborhood: 'Fairfax District',
    lat: 34.0809,
    lng: -118.3607,
    severity: 'high',
    source: 'FBI',
    status: 'verified',
    campus_id: null,
    created_at: '2024-10-09T12:00:00Z',
  },
  // --- West Hollywood ---
  {
    id: 'demo-incident-024',
    category: 'online_threat',
    description:
      'A West Hollywood synagogue\'s NextDoor page was flooded with antisemitic posts from newly created accounts after they announced expanded holiday programming. The accounts appeared coordinated and were reported to the platform.',
    occurred_at: '2024-02-28T19:00:00Z',
    neighborhood: 'West Hollywood',
    lat: 34.0909,
    lng: -118.3639,
    severity: 'low',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-03-01T08:00:00Z',
  },
  {
    id: 'demo-incident-025',
    category: 'harassment',
    description:
      'Two Jewish men were subjected to prolonged verbal harassment and antisemitic slurs by a stranger at a WeHo coffee shop for approximately 20 minutes. Staff asked the individual to leave but he continued until escorted out.',
    occurred_at: '2024-04-25T09:30:00Z',
    neighborhood: 'West Hollywood',
    lat: 34.0880,
    lng: -118.3606,
    severity: 'low',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-04-25T11:00:00Z',
  },
  {
    id: 'demo-incident-026',
    category: 'vandalism',
    description:
      'A Star of David etched into the sidewalk in front of a Sunset Strip business was deliberately chipped away and replaced with antisemitic graffiti. The building owner estimated repair costs at $400.',
    occurred_at: '2024-07-04T02:00:00Z',
    neighborhood: 'West Hollywood',
    lat: 34.0918,
    lng: -118.3625,
    severity: 'low',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-07-04T10:00:00Z',
  },
  {
    id: 'demo-incident-027',
    category: 'harassment',
    description:
      'A Jewish family was targeted with antisemitic comments by their neighbor, who also placed antisemitic flyers under their door repeatedly over the course of a week. When the family confronted the neighbor, police were called to de-escalate the situation.',
    occurred_at: '2024-09-17T17:30:00Z',
    neighborhood: 'West Hollywood',
    lat: 34.0893,
    lng: -118.3641,
    severity: 'medium',
    source: 'LAPD',
    status: 'verified',
    campus_id: null,
    created_at: '2024-09-18T09:00:00Z',
  },
  // --- Mid-Wilshire ---
  {
    id: 'demo-incident-028',
    category: 'vandalism',
    description:
      'Antisemitic graffiti including the phrase "Jews lie" was spray-painted on the wall of a Mid-Wilshire parking structure adjacent to a building housing several Jewish-owned businesses. The graffiti covered approximately 12 square feet.',
    occurred_at: '2024-03-11T00:30:00Z',
    neighborhood: 'Mid-Wilshire',
    lat: 34.0641,
    lng: -118.3381,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-03-11T08:00:00Z',
  },
  {
    id: 'demo-incident-029',
    category: 'harassment',
    description:
      'A Jewish woman wearing a chai necklace was confronted at a Miracle Mile bus stop by a man who made derogatory comments about Jewish people and refused to move away when asked. A bystander filmed the incident.',
    occurred_at: '2024-06-13T08:15:00Z',
    neighborhood: 'Mid-Wilshire',
    lat: 34.0607,
    lng: -118.3348,
    severity: 'low',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-06-13T10:00:00Z',
  },
  {
    id: 'demo-incident-030',
    category: 'online_threat',
    description:
      'The Los Angeles Museum of the Holocaust received a threatening email claiming it would be targeted during the upcoming anniversary commemoration event. Law enforcement determined it was credible enough to increase event security substantially.',
    occurred_at: '2024-04-28T14:00:00Z',
    neighborhood: 'Mid-Wilshire',
    lat: 34.0626,
    lng: -118.3394,
    severity: 'high',
    source: 'FBI',
    status: 'verified',
    campus_id: null,
    created_at: '2024-04-29T09:00:00Z',
  },
  // --- Silver Lake ---
  {
    id: 'demo-incident-031',
    category: 'harassment',
    description:
      'A Jewish-owned bookstore in Silver Lake was picketed by a small group carrying antisemitic signs for three hours on a Saturday afternoon. Police monitored from a distance but made no arrests as the protest remained technically lawful.',
    occurred_at: '2024-05-04T13:00:00Z',
    neighborhood: 'Silver Lake',
    lat: 34.0886,
    lng: -118.2716,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-05-04T16:00:00Z',
  },
  {
    id: 'demo-incident-032',
    category: 'vandalism',
    description:
      'A Star of David was defaced with a swastika spray-painted over it on the exterior wall of a community center in Silver Lake. The vandalism was discovered the morning before a Jewish cultural film screening was scheduled. Estimated damage: $800.',
    occurred_at: '2024-07-18T02:00:00Z',
    neighborhood: 'Silver Lake',
    lat: 34.0845,
    lng: -118.2694,
    severity: 'high',
    source: 'ADL',
    status: 'verified',
    campus_id: null,
    created_at: '2024-07-18T09:00:00Z',
  },
  {
    id: 'demo-incident-033',
    category: 'online_threat',
    description:
      'A Silver Lake resident who runs a Jewish heritage YouTube channel received a series of death threats in their video comments after posting content about their family\'s Holocaust history. YouTube removed the comments but the channel creator filed a police report.',
    occurred_at: '2024-10-02T20:00:00Z',
    neighborhood: 'Silver Lake',
    lat: 34.0877,
    lng: -118.2735,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-10-03T09:00:00Z',
  },
  // --- Los Feliz ---
  {
    id: 'demo-incident-034',
    category: 'harassment',
    description:
      'A Jewish family celebrating their son\'s bar mitzvah was confronted outside a Los Feliz restaurant by a man who berated them with antisemitic commentary for several minutes. Other diners intervened and the individual left before police arrived.',
    occurred_at: '2024-04-06T14:30:00Z',
    neighborhood: 'Los Feliz',
    lat: 34.1098,
    lng: -118.2953,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-04-06T16:00:00Z',
  },
  {
    id: 'demo-incident-035',
    category: 'vandalism',
    description:
      'Antisemitic flyers were distributed throughout a Los Feliz apartment complex overnight, placed under doors and in mailboxes. The flyers contained Holocaust denial claims and contact information for a known white supremacist organization.',
    occurred_at: '2024-08-23T04:00:00Z',
    neighborhood: 'Los Feliz',
    lat: 34.1078,
    lng: -118.2916,
    severity: 'medium',
    source: 'ADL',
    status: 'verified',
    campus_id: null,
    created_at: '2024-08-23T08:00:00Z',
  },
  {
    id: 'demo-incident-036',
    category: 'other',
    description:
      'A Jewish religious school in Los Feliz received repeated hang-up calls mixed with brief antisemitic slurs over three school days. The caller ID was spoofed and law enforcement traced the calls to a VOIP service outside California.',
    occurred_at: '2024-11-12T10:00:00Z',
    neighborhood: 'Los Feliz',
    lat: 34.1109,
    lng: -118.2928,
    severity: 'medium',
    source: 'LAPD',
    status: 'verified',
    campus_id: null,
    created_at: '2024-11-12T14:00:00Z',
  },
  // --- Valley Village ---
  {
    id: 'demo-incident-037',
    category: 'harassment',
    description:
      'An individual drove slowly past a Valley Village synagogue on multiple occasions over two weeks, shouting antisemitic slurs at congregants arriving for services. Security cameras captured the vehicle license plate and LAPD identified the suspect.',
    occurred_at: '2024-03-17T10:30:00Z',
    neighborhood: 'Valley Village',
    lat: 34.1739,
    lng: -118.4032,
    severity: 'medium',
    source: 'LAPD',
    status: 'verified',
    campus_id: null,
    created_at: '2024-03-18T09:00:00Z',
  },
  {
    id: 'demo-incident-038',
    category: 'vandalism',
    description:
      'The gate of a Valley Village Jewish day school was spray-painted with an antisemitic message referencing the current geopolitical conflict. The graffiti was discovered by the principal at 6:45 AM before students arrived.',
    occurred_at: '2024-06-09T03:00:00Z',
    neighborhood: 'Valley Village',
    lat: 34.1711,
    lng: -118.4004,
    severity: 'high',
    source: 'ADL',
    status: 'verified',
    campus_id: null,
    created_at: '2024-06-09T08:00:00Z',
  },
  {
    id: 'demo-incident-039',
    category: 'harassment',
    description:
      'A Jewish man walking to synagogue in Valley Village on Shabbat morning was followed for two blocks by an individual making antisemitic comments. The man entered a nearby shop for safety and the suspect departed without further confrontation.',
    occurred_at: '2024-09-28T09:15:00Z',
    neighborhood: 'Valley Village',
    lat: 34.1755,
    lng: -118.4013,
    severity: 'low',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-09-28T11:00:00Z',
  },
  // --- Sherman Oaks ---
  {
    id: 'demo-incident-040',
    category: 'online_threat',
    description:
      'A Sherman Oaks synagogue Yelp page was targeted with one-star antisemitic reviews from accounts with no prior activity. The coordinated review bombing included several posts referencing a violent conspiracy theory about Jewish institutions.',
    occurred_at: '2024-02-22T15:00:00Z',
    neighborhood: 'Sherman Oaks',
    lat: 34.1522,
    lng: -118.4501,
    severity: 'low',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-02-23T09:00:00Z',
  },
  {
    id: 'demo-incident-041',
    category: 'vandalism',
    description:
      'A Sherman Oaks menorah display in a community park was toppled and its Star of David decorations smashed during the night. The display had been erected for Hanukkah. Damage was estimated at $350.',
    occurred_at: '2024-12-06T00:00:00Z',
    neighborhood: 'Sherman Oaks',
    lat: 34.1494,
    lng: -118.4473,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-12-06T08:30:00Z',
  },
  {
    id: 'demo-incident-042',
    category: 'harassment',
    description:
      'A middle-school student from a Jewish family reported being called antisemitic slurs repeatedly by classmates at a Sherman Oaks school. The school investigated and suspended two students. The family reported the incident to the ADL.',
    occurred_at: '2024-10-15T12:00:00Z',
    neighborhood: 'Sherman Oaks',
    lat: 34.1529,
    lng: -118.4518,
    severity: 'medium',
    source: 'ADL',
    status: 'verified',
    campus_id: null,
    created_at: '2024-10-15T17:00:00Z',
  },
  // --- Encino ---
  {
    id: 'demo-incident-043',
    category: 'vandalism',
    description:
      'Swastika symbols were drawn in permanent marker on the exterior walls of three Jewish-owned businesses in an Encino strip mall. The businesses share a parking lot. Surveillance footage captured a partial image of the suspect.',
    occurred_at: '2024-05-17T22:00:00Z',
    neighborhood: 'Encino',
    lat: 34.1529,
    lng: -118.5023,
    severity: 'medium',
    source: 'LAPD',
    status: 'verified',
    campus_id: null,
    created_at: '2024-05-18T09:00:00Z',
  },
  {
    id: 'demo-incident-044',
    category: 'harassment',
    description:
      'A Jewish retiree exercising in an Encino park was approached and subjected to conspiracy-theory-laced antisemitic rants by an individual for approximately 15 minutes. The man recorded part of the encounter on his phone.',
    occurred_at: '2024-07-11T08:30:00Z',
    neighborhood: 'Encino',
    lat: 34.1489,
    lng: -118.4997,
    severity: 'low',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-07-11T11:00:00Z',
  },
  // --- Studio City ---
  {
    id: 'demo-incident-045',
    category: 'online_threat',
    description:
      'A Studio City rabbi who posts Torah commentary on Twitter/X was targeted by an antisemitic pile-on after mentioning the High Holidays. The campaign included doxxing attempts, with the rabbi\'s home address posted in several reply threads.',
    occurred_at: '2024-09-05T18:00:00Z',
    neighborhood: 'Studio City',
    lat: 34.1397,
    lng: -118.3886,
    severity: 'high',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-09-06T09:00:00Z',
  },
  {
    id: 'demo-incident-046',
    category: 'harassment',
    description:
      'Jewish production company employees were harassed outside their Studio City office by protesters who had learned the company had a co-production deal with an Israeli broadcaster. Protesters blocked the entrance for roughly 40 minutes.',
    occurred_at: '2024-11-19T12:00:00Z',
    neighborhood: 'Studio City',
    lat: 34.1372,
    lng: -118.3855,
    severity: 'medium',
    source: 'LAPD',
    status: 'verified',
    campus_id: null,
    created_at: '2024-11-19T15:00:00Z',
  },
  // --- Santa Monica ---
  {
    id: 'demo-incident-047',
    category: 'vandalism',
    description:
      'Antisemitic graffiti was spray-painted on the walls of a Santa Monica apartment building with a large Jewish tenant population. Multiple units\' door signs identifying Jewish holidays were torn down the same night.',
    occurred_at: '2024-04-19T01:30:00Z',
    neighborhood: 'Santa Monica',
    lat: 34.0264,
    lng: -118.4968,
    severity: 'medium',
    source: 'ADL',
    status: 'verified',
    campus_id: null,
    created_at: '2024-04-19T08:00:00Z',
  },
  {
    id: 'demo-incident-048',
    category: 'harassment',
    description:
      'A Jewish man wearing religious attire was surrounded by three individuals on the Santa Monica Promenade who refused to let him pass and chanted slogans inches from his face. Bystanders intervened and called 911.',
    occurred_at: '2024-07-20T16:45:00Z',
    neighborhood: 'Santa Monica',
    lat: 34.0234,
    lng: -118.4928,
    severity: 'high',
    source: 'LAPD',
    status: 'verified',
    campus_id: null,
    created_at: '2024-07-20T18:00:00Z',
  },
  {
    id: 'demo-incident-049',
    category: 'online_threat',
    description:
      'A Santa Monica Jewish community organization\'s email list was apparently breached and its subscribers received a threatening mass email containing antisemitic imagery and a warning not to attend upcoming events. The organization notified authorities and cybersecurity professionals.',
    occurred_at: '2024-10-27T11:00:00Z',
    neighborhood: 'Santa Monica',
    lat: 34.0259,
    lng: -118.4956,
    severity: 'high',
    source: 'CSI',
    status: 'verified',
    campus_id: null,
    created_at: '2024-10-27T14:00:00Z',
  },
  // --- Culver City ---
  {
    id: 'demo-incident-050',
    category: 'harassment',
    description:
      'A Culver City synagogue received a phone call in which the caller made specific threats about the upcoming Yom Kippur service, referencing the number of congregants expected and the security arrangements. The call was recorded and law enforcement began an investigation.',
    occurred_at: '2024-09-25T15:30:00Z',
    neighborhood: 'Culver City',
    lat: 34.0224,
    lng: -118.3945,
    severity: 'high',
    source: 'FBI',
    status: 'verified',
    campus_id: null,
    created_at: '2024-09-25T17:00:00Z',
  },
  {
    id: 'demo-incident-051',
    category: 'vandalism',
    description:
      'A menorah mounted on the front of a Culver City Jewish family\'s home was stolen during the night. A note containing an antisemitic slur was left in its place. The family had lived in the neighborhood for 22 years.',
    occurred_at: '2024-12-12T02:00:00Z',
    neighborhood: 'Culver City',
    lat: 34.0193,
    lng: -118.3956,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-12-12T09:00:00Z',
  },
  // --- Brentwood ---
  {
    id: 'demo-incident-052',
    category: 'harassment',
    description:
      'A Jewish woman was verbally accosted at a Brentwood Whole Foods by a man who accused her of supporting atrocities based on the Hebrew lettering on her tote bag. Staff asked the man to leave and he complied only after 10 minutes of confrontation.',
    occurred_at: '2024-05-31T11:30:00Z',
    neighborhood: 'Brentwood',
    lat: 34.0513,
    lng: -118.4763,
    severity: 'low',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-05-31T13:00:00Z',
  },
  {
    id: 'demo-incident-053',
    category: 'online_threat',
    description:
      'A Brentwood private Jewish school\'s phone line was targeted with a robocall campaign using AI-generated voices making antisemitic threats, referencing the school by name. The campaign lasted over two days before the phone provider blocked the source numbers.',
    occurred_at: '2024-08-05T09:00:00Z',
    neighborhood: 'Brentwood',
    lat: 34.0482,
    lng: -118.4733,
    severity: 'high',
    source: 'CSI',
    status: 'verified',
    campus_id: null,
    created_at: '2024-08-05T12:00:00Z',
  },
  // --- Downtown LA ---
  {
    id: 'demo-incident-054',
    category: 'assault',
    description:
      'A Jewish man in a business suit wearing a kippah was attacked near Pershing Square by an individual who punched him and shouted antisemitic slurs. The victim required medical attention for a cut above his eyebrow. The suspect was apprehended two blocks away.',
    occurred_at: '2024-06-27T18:00:00Z',
    neighborhood: 'Downtown LA',
    lat: 34.0418,
    lng: -118.2487,
    severity: 'high',
    source: 'LAPD',
    status: 'verified',
    campus_id: null,
    created_at: '2024-06-27T20:00:00Z',
  },
  {
    id: 'demo-incident-055',
    category: 'harassment',
    description:
      'Antisemitic flyers targeting a downtown Jewish-owned law firm were distributed in the building\'s lobby and left on conference room chairs during a public event. The flyers claimed Jewish attorneys were part of a broader conspiracy.',
    occurred_at: '2024-09-10T13:00:00Z',
    neighborhood: 'Downtown LA',
    lat: 34.0385,
    lng: -118.2453,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-09-10T15:00:00Z',
  },
  // --- Koreatown ---
  {
    id: 'demo-incident-056',
    category: 'vandalism',
    description:
      'A Jewish-owned dry cleaner in Koreatown had its windows shattered and antisemitic graffiti painted on the interior walls. It appeared the business was specifically targeted based on a mezuzah visible on the doorframe. Damage exceeded $3,000.',
    occurred_at: '2024-07-07T03:00:00Z',
    neighborhood: 'Koreatown',
    lat: 34.0600,
    lng: -118.3026,
    severity: 'high',
    source: 'LAPD',
    status: 'verified',
    campus_id: null,
    created_at: '2024-07-07T09:00:00Z',
  },
  {
    id: 'demo-incident-057',
    category: 'harassment',
    description:
      'A Koreatown resident reported that a neighbor had been slipping antisemitic notes under her door for weeks. When she confronted the neighbor, they made threatening statements and the situation escalated to a police welfare check.',
    occurred_at: '2024-10-21T18:00:00Z',
    neighborhood: 'Koreatown',
    lat: 34.0579,
    lng: -118.2985,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2024-10-21T20:00:00Z',
  },
  // --- 2025 incidents ---
  {
    id: 'demo-incident-058',
    category: 'harassment',
    description:
      'During a Yom HaShoah commemoration event in Westwood, a small group of counter-demonstrators with antisemitic signs positioned themselves at the entrance. Attendees were subjected to verbal taunts as they arrived for the memorial ceremony.',
    occurred_at: '2025-01-27T17:00:00Z',
    neighborhood: 'Westwood',
    lat: 34.0659,
    lng: -118.4437,
    severity: 'medium',
    source: 'ADL',
    status: 'verified',
    campus_id: 'campus-demo-university',
    created_at: '2025-01-28T09:00:00Z',
  },
  {
    id: 'demo-incident-059',
    category: 'online_threat',
    description:
      'A Beverly Hills Chabad received a Telegram message from an anonymous account threatening to disrupt their upcoming Passover seder. The message included what appeared to be a photo of the building exterior, suggesting the sender had been on-site.',
    occurred_at: '2025-02-14T20:00:00Z',
    neighborhood: 'Beverly Hills',
    lat: 34.0763,
    lng: -118.3987,
    severity: 'high',
    source: 'FBI',
    status: 'verified',
    campus_id: null,
    created_at: '2025-02-15T09:00:00Z',
  },
  {
    id: 'demo-incident-060',
    category: 'vandalism',
    description:
      'A Pico-Robertson kosher grocery store found that its parking lot had been painted with antisemitic slogans overnight. The paint covered several parking spaces and was seen by dozens of customers before staff could begin cleanup. Estimated damage: $1,100.',
    occurred_at: '2025-03-05T02:30:00Z',
    neighborhood: 'Pico-Robertson',
    lat: 34.0496,
    lng: -118.3881,
    severity: 'medium',
    source: 'LAPD',
    status: 'verified',
    campus_id: null,
    created_at: '2025-03-05T09:00:00Z',
  },
  {
    id: 'demo-incident-061',
    category: 'assault',
    description:
      'A Jewish teenager wearing a Hebrew school sweatshirt was shoved and punched in the chest by an older individual at a Valley Village bus stop. The attacker shouted antisemitic slurs during the assault. The victim\'s parent filed charges and the incident was classified as a hate crime.',
    occurred_at: '2025-04-17T15:45:00Z',
    neighborhood: 'Valley Village',
    lat: 34.1727,
    lng: -118.4036,
    severity: 'high',
    source: 'LAPD',
    status: 'verified',
    campus_id: null,
    created_at: '2025-04-17T17:30:00Z',
  },
  {
    id: 'demo-incident-062',
    category: 'harassment',
    description:
      'Employees at a Jewish nonprofit in the Fairfax District were subjected to a sustained campaign of harassment by an individual who called repeatedly with antisemitic commentary before the calls were blocked and law enforcement notified.',
    occurred_at: '2025-05-08T10:00:00Z',
    neighborhood: 'Fairfax District',
    lat: 34.0770,
    lng: -118.3604,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2025-05-08T14:00:00Z',
  },
  {
    id: 'demo-incident-063',
    category: 'online_threat',
    description:
      'A Silver Lake Jewish-owned art gallery was targeted on multiple social media platforms with coordinated antisemitic posts following its announcement of an exhibition exploring Jewish identity. The gallery owner received private messages containing specific threats to the upcoming opening.',
    occurred_at: '2025-06-14T18:00:00Z',
    neighborhood: 'Silver Lake',
    lat: 34.0872,
    lng: -118.2679,
    severity: 'medium',
    source: 'community',
    status: 'verified',
    campus_id: null,
    created_at: '2025-06-15T09:00:00Z',
  },
  {
    id: 'demo-incident-064',
    category: 'other',
    description:
      'A Sherman Oaks Jewish day school received a bomb threat via email on the morning of a major school event. The school was evacuated and police swept the premises. No device was found and the threat was ultimately deemed non-credible, but the disruption impacted over 400 students.',
    occurred_at: '2025-08-29T08:30:00Z',
    neighborhood: 'Sherman Oaks',
    lat: 34.1511,
    lng: -118.4509,
    severity: 'high',
    source: 'FBI',
    status: 'verified',
    campus_id: null,
    created_at: '2025-08-29T10:00:00Z',
  },
  {
    id: 'demo-incident-065',
    category: 'assault',
    description:
      'A Jewish woman was shoved to the ground outside a Brentwood synagogue after afternoon services by an individual who made antisemitic remarks. She suffered a bruised knee and wrist. Witnesses detained the suspect until police arrived. The incident was charged as a hate crime assault.',
    occurred_at: '2025-10-11T17:30:00Z',
    neighborhood: 'Brentwood',
    lat: 34.0502,
    lng: -118.4775,
    severity: 'high',
    source: 'LAPD',
    status: 'verified',
    campus_id: null,
    created_at: '2025-10-11T19:00:00Z',
  },
];

export function isDemoMode(): boolean {
  return (
    !process.env.NEXT_PUBLIC_SUPABASE_URL ||
    !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
    process.env.NEXT_PUBLIC_DEMO_MODE === 'true'
  );
}
